# Generated by Django 5.1.1 on 2025-02-08 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('valid_from', models.DateTimeField(verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(verbose_name='Дійсний по')),
                ('discount', models.IntegerField(help_text='Відсоток знижки (від 0 до 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('active', models.BooleanField(verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купони',
            },
        ),
    ]
